// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB72u0IZKeLP2ar9077kDSk2U6o4VA3MnE',
    appId: '1:520863827871:web:b9a8af571541d5f4649faa',
    messagingSenderId: '520863827871',
    projectId: 'poker2-a69d2',
    authDomain: 'poker2-a69d2.firebaseapp.com',
    storageBucket: 'poker2-a69d2.firebasestorage.app',
    measurementId: 'G-WLWJW231Q9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe_rne-3LlXCnoOHjamP49xiPrtN2WcvI',
    appId: '1:520863827871:android:38397a9d49af36b6649faa',
    messagingSenderId: '520863827871',
    projectId: 'poker2-a69d2',
    storageBucket: 'poker2-a69d2.firebasestorage.app',
  );
}
