// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDATFR6g_USmIw3W0mRnPyXexYhL2cLPeE',
    appId: '1:168868210085:web:778c39d5802e64eb24b44c',
    messagingSenderId: '168868210085',
    projectId: 'projectf-49e7f',
    authDomain: 'projectf-49e7f.firebaseapp.com',
    storageBucket: 'projectf-49e7f.firebasestorage.app',
    measurementId: 'G-GGG95BJ5DE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0PNFp5MGciVwSdsE8QnqGPRBw9XtFlHU',
    appId: '1:168868210085:android:2a7283f610e29ebe24b44c',
    messagingSenderId: '168868210085',
    projectId: 'projectf-49e7f',
    storageBucket: 'projectf-49e7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv1RTLfxS8zjSl1d9pkc69x2O7ZHpsRLY',
    appId: '1:168868210085:ios:565c6075a45e935124b44c',
    messagingSenderId: '168868210085',
    projectId: 'projectf-49e7f',
    storageBucket: 'projectf-49e7f.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv1RTLfxS8zjSl1d9pkc69x2O7ZHpsRLY',
    appId: '1:168868210085:ios:565c6075a45e935124b44c',
    messagingSenderId: '168868210085',
    projectId: 'projectf-49e7f',
    storageBucket: 'projectf-49e7f.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDATFR6g_USmIw3W0mRnPyXexYhL2cLPeE',
    appId: '1:168868210085:web:9a27f4a67213f71224b44c',
    messagingSenderId: '168868210085',
    projectId: 'projectf-49e7f',
    authDomain: 'projectf-49e7f.firebaseapp.com',
    storageBucket: 'projectf-49e7f.firebasestorage.app',
    measurementId: 'G-G6HR70MHC0',
  );
}
